<%

const a = 1;
const b = "bbb";
const c = 0xABCDEF;
const d = native String.toString();
const e = 1+1;
const f = e+1;

assertEquals(2, e);
assertEquals(3, f);

{
    const a = 2;
    const b = "bbb" + "aaa";
    assertEquals(2, a);
    assertEquals("bbbaaa", b);
}

%>