<%

{
    
    var a = "A";
    var b = "B";
    {
        import "/import1.wit";

        var b;
        var func;

        var c = "c";

        assertSame(a, super.a);
        assertSame(c, func(c));

        assertNotSame(b, super.b);
        assertEquals(b, "b");

    }
    {
        var b;
        var b_1;
        import "/import1.wit" a,b_1=b;

        var func;

        var c = "c";

        assertSame(a, super.a);

        assertEquals(a, "a");

        assertNull(func);
        assertNull(b);

        assertEquals(b_1, "b");

    }
    {
        import "/import1.wit" {"1":"1","2":"2"} a,b;
        var a;
        var b;
        var c = {"1":"1","2":"2"};
        import "/import1.wit" {c} a,b;
    }

}


%>