<%

import "/junit-assert.wit";

var assertEquals;
var assertNotNull;

{
    assertNotNull($GLOBAL);
    assertEquals($GLOBAL["one"], 1);
    assertEquals($GLOBAL["two"], 2);
    assertEquals($GLOBAL["string"], "string");
    assertEquals($GLOBAL["string2"], "string2");
}
%>