<%

import "/junit-assert.wit";

var assertEquals;
var assertNotEquals;
{

    assertEquals(3, 1+2);
    assertEquals(-1, 1-2);
    assertEquals(4, 2*2);
    assertEquals(2, 5/2);
    assertEquals(1, 5%2);
    assertEquals(20,5 << 2);
    assertEquals(1, 5 >> 2);
    assertEquals(-2, -5 >> 2);
    assertEquals(1073741822, -5 >>> 2);


    // ？:
    assertEquals(1, true?1:2);
    assertEquals(1, 1?:2);
    assertEquals(2, null?:2);

}
{
    //Int Step test

    //asc
    var one = 1;
    var tree = 3; 
    var i = 1;
    for(num : i .. tree){
        assertEquals(i, num);
        i++;
    }
    assertEquals(i, 4);

    //desc
    i = 3;
    for(num : i .. one){
        assertEquals(i, num);
        i--;
    }
    assertEquals(i, 0);

}


%>