<%

import "/junit-assert.wit";

var assertEquals;
var assertNotEquals;
var assertSame;
var assertNotSame;
var assertNotNull;

{
    var a = "a";
    var b = "b";
    {
        var b = "b";
        assertSame(a, super.a);
        assertNotSame(b, super.b);
        assertEquals(a, "a");
        {
            assertSame(a, super.a);
            assertSame(a, super.super.this.a);
            assertNotSame(super.b, super.super.b);
            assertEquals(a, "a");
        }
    }

}
{
    var $;
    var _;
    var __;
    var $$;
}
{
    //
    request = 1;
    session = 1;
    session = 1;
    request2 = 1;
}
{
    //global
    $GLOBAL["aaa"] = "AAA";
    $GLOBAL["bbb"] = "BBB";

    assertNotNull($GLOBAL);
    assertEquals($GLOBAL["aaa"], "AAA");
    assertEquals($GLOBAL["bbb"], "BBB");

    // cutsom register
    assertEquals("MY_CONST", MY_CONST);
    assertEquals("MY_CONST_2", MY_CONST_2);
    assertEquals("MY_GLOBAL", MY_GLOBAL);
    assertEquals("MY_GLOBAL_2", MY_GLOBAL_2);

    MY_GLOBAL = "a new value";
    assertEquals("a new value", MY_GLOBAL);

}


%>
