assertEquals("", CONST_STRING_BUILDER.~toString());
assertEquals(0, CONST_ATOMIC_INT.~get());

assertEquals("", CONST_STRING_BUILDER + "");
assertEquals(0, CONST_ATOMIC_INT + 0);

assertEquals("abc", CONST_STRING_BUILDER + "abc");
assertEquals(100, CONST_ATOMIC_INT + 100);

// changed
CONST_STRING_BUILDER.~append("XYZ");
CONST_ATOMIC_INT.~set(1024);

assertEquals("XYZ", CONST_STRING_BUILDER.~toString());
assertEquals(1024, CONST_ATOMIC_INT.~get());

assertEquals("XYZabc", CONST_STRING_BUILDER + "abc");
assertEquals(1124, CONST_ATOMIC_INT + 100);

// IR asserts
CONST_STRING_BUILDER.~setLength(0)
CONST_STRING_BUILDER.~append("XYZ")
CONST_ATOMIC_INT.~set(1024)
var obj

obj = [? "assert:ConstantValue" : 1 ?]
assertEquals(1, obj);
obj = [? "assert:ConstantValue" : "abc" ?]
assertEquals("abc", obj);
obj = [? "assert:ConstantValue" : CONST_STRING_BUILDER ?]
assertEquals("XYZ", obj.~toString());

obj = [? "assert:ConstantValue" : 1 + 2 ?]
assertEquals(3, obj);
obj = [? "assert:ConstantValue" : "abc" + "xyz" ?]
assertEquals("abcxyz", obj);
obj = [? "assert:ConstantValue" : "abc" + 123 ?]
assertEquals("abc123", obj);

obj = [? "assert:NotConstantValue" : 100 + CONST_ATOMIC_INT ?]
obj = [? "assert:NotConstantValue" : CONST_ATOMIC_INT + 100 ?]
assertEquals(1124, obj);
obj = [? "assert:NotConstantValue" : "abc" + CONST_STRING_BUILDER ?]
obj = [? "assert:NotConstantValue" : CONST_STRING_BUILDER + "abc" ?]
assertEquals("XYZabc", obj);


obj = [? "assert:ConstantValue" : 100 && 200 ?]
assertEquals(200, obj);
obj = [? "assert:ConstantValue" : 100 && 200 * 100 ?]
assertEquals(20000, obj);
obj = [? "assert:ConstantValue" : 100 || 200 ?]
assertEquals(100, obj);


const N100 = 100;

obj = [? "assert:ConstantValue" : -100 ?]
assertEquals(-100, obj);
obj = [? "assert:ConstantValue" : -N100 ?]
assertEquals(-100, obj);

obj = [? "assert:ConstantValue" : !-N100 ?]
assertFalse(obj);
obj = [? "assert:ConstantValue" : !100 ?]
assertFalse(obj);
obj = [? "assert:ConstantValue" : !!100 ?]
assertTrue(obj);
obj = [? "assert:ConstantValue" : !!!100 ?]
assertFalse(obj);

obj = [? "assert:NotConstantValue" : !CONST_ATOMIC_INT ?]
assertFalse(obj);

obj = [? "assert:ConstantValue" : false && CONST_ATOMIC_INT ?]
assertFalse(obj);
obj = [? "assert:ConstantValue" : "" && CONST_ATOMIC_INT ?]
assertEquals("", obj);
obj = [? "assert:ConstantValue" : 100 || CONST_ATOMIC_INT ?]
assertEquals(100, obj);

obj = [? "assert:ConstantValue" : true && CONST_ATOMIC_INT ?]
assertEquals(CONST_ATOMIC_INT, obj);
obj = [? "assert:ConstantValue" : false || CONST_ATOMIC_INT ?]
assertEquals(CONST_ATOMIC_INT, obj);

obj = [? "assert:NotConstantValue" : CONST_ATOMIC_INT && 100 ?]
assertEquals(100, obj);
obj = [? "assert:NotConstantValue" : CONST_ATOMIC_INT || 100 ?]
assertEquals(CONST_ATOMIC_INT, obj);
