{

    var [a,b]= ["a", "b"];

    var [A,B] = [a,b];

    assertEquals("a", a);
    assertEquals("b", b);

    assertEquals("a", A);
    assertEquals("b", B);
}

{

    var [a, b]= ["a", "b"];

    assertEquals("a", a);
    assertEquals("b", b);

    [a, b] = [b, a];

    assertEquals("b", a);
    assertEquals("a", b);

}

{
    var a,b,c;

    [a,b,c] = [0,1,2,3,4];

    assertEquals(0, a);
    assertEquals(1, b);
    assertEquals(2, c);


    [a,b,c] = [5,6,7];

    assertEquals(5, a);
    assertEquals(6, b);
    assertEquals(7, c);

    [a,b,c] = [10,11];

    assertEquals(10, a);
    assertEquals(11, b);
    assertNull(c);


    [a,b,c] = [15];

    assertEquals(15, a);
    assertNull(b);
    assertNull(c);


    [a,b,c] = [];

    assertNull(a);
    assertNull(b);
    assertNull(c);

    [a] = [];

    assertNull(a);
}

{

    var [a,b,c,d,e,f] = 1..10;

    assertEquals(1, a);
    assertEquals(2, b);
    assertEquals(3, c);
    assertEquals(4, d);
    assertEquals(5, e);
    assertEquals(6, f);
}

{

    var new_int_arr = native [] int;

    var arr = new_int_arr(10);

    [arr[0],arr[1],arr[2],arr[3]] = 1..10;


    assertEquals(1, arr[0]);
    assertEquals(2, arr[1]);
    assertEquals(3, arr[2]);
    assertEquals(4, arr[3]);
    assertEquals(0, arr[4]);
    assertEquals(0, arr[5]);

    [arr[5],arr[6],arr[7],arr[8],arr[9]] = arr;

    assertEquals(1, arr[5]);
    assertEquals(2, arr[6]);
    assertEquals(3, arr[7]);
    assertEquals(4, arr[8]);
    assertEquals(0, arr[9]);
}

{
    var a, b;

    [a, b] = (x -> [1,2])();

    assertEquals(1, a);
    assertEquals(2, b);
}
