const a = 1;
const b = "bbb";
const c = 0xABCDEF;
const e = 1+1;
const f = e+1;
const toString = native Object.toString();
const oneString = toString(1);
const toString2 = "xxx".~toString()
const temp = noop(
  "yyy".~toString()
)

assertEquals(2, e);
assertEquals(3, f);
assertEquals("1", oneString);
assertEquals("xxx", toString2);

{
    const a = 2;
    const b = "bbb" + "aaa";
    assertEquals(2, a);
    assertEquals("bbbaaa", b);
}
{

    const arr = ["xx", a, b,c];

    assertEquals("xx", arr[0]);
    assertEquals(a, arr[1]);
    assertEquals(b, arr[2]);
    assertEquals(c, arr[3]);

}
{

    const map = {
        "1": a,
        "2": b
    };

    assertEquals(a, map["1"]);
    assertEquals(b, map["2"]);

}

{
    // set by plugins
    assertTrue(PLUGIN_CONFIG_FLAG)
    assertTrue(PLUGIN_SPI_FLAG)
}
