<%
{
    //empty block
}
{
    for(i : 3..6){
        //empty block
    }else{
        //empty block
    }
}
{
    var new_ints = native [int];
    var ints = new_ints(4);
    ints[0] = 3;
    ints[1] = 4;
    ints[2] = 5;
    ints[3] = 6;
    assertEquals(4, ints.size);
    var s = "";
    for(i : ints){
        s +=  for.iter.isOdd? "1":"0";
    }
    assertEquals("1010", s);
}
{
    var s = "";
    for(i : 3..6){
        s +=  for.iter.isOdd? "1":"0";
    }
    assertEquals("1010", s);
}
{
    var i = 0;
    var counter = 3; 
    for(i : 3..6){
        assertEquals(i, counter);
        counter++;
    }else{
        //assert shouldn't run here
        assertNotNull(null);
    }
    assertEquals(i, 0);
    assertEquals(counter, 7);
}
{
    for(i : 3..6){
    }else{
        //assert shouldn't run here
        assertNotNull(null);
    }
}
{
    var s = "";
    for(i -> (i & 1) == 1 : 3..6){
        s +=  i;
    }
    assertEquals("35", s);
}
{
    var s = "";
    for(i -> {return (i & 1) == 1;} : 3..6){
        s +=  i;
    }
    assertEquals("35", s);
}

%>
