<%
{
    var c;
    var func = function(){
        var a;
        var b;

        {
            var func2 = function(){
                assertTrue(true);
                return c;
            };
            var func3 = function{
                assertTrue(true);
                return c;
            };
            var func4 = #(a,b){
                assertTrue(true);
                return c;
            };
            var func5 = #{
                assertTrue(true);
                return c;
            };
            func2();
            func3();
            func4();
            func5();
        }
    };
    func();
}
{
    var c;
    function func(){
        var a;
        var b;
        {
            function func2(){
                assertTrue(true);
                return c;
            }
            function func4(a,b){
                assertTrue(true);
                return c;
            }
            func2();
            func4();
        }
    }
    func();
}

{
    var func = function(a, b){
        return b;
    };

    assertEquals(1, func(null, 1));
    assertEquals("b", func(null, "b"));
    assertEquals(null, func());
    assertEquals(null, func(null));
    assertEquals(null, func("a"));
}
%>