<%

{
    
    var a = "A";
    var b = "B";
    {
        import "etc/importTest.import.wit";

        var b;
        var func;

        var c = "c";

        assertSame(a, super.a);
        assertSame(c, func(c));

        assertNotSame(b, super.b);
        assertEquals(b, "b");

    }
    {
        var b;
        var b_1;
        import "etc/importTest.import.wit" a,b_1=b;

        var func;

        var c = "c";

        assertSame(a, super.a);

        assertEquals(a, "a");

        assertNull(func);
        assertNull(b);

        assertEquals(b_1, "b");

    }
    {
        import "etc/importTest.import.wit" {"1":"1","2":"2"} a,b;
        var a;
        var b;
    }

}


%>