<%
var new_list = native new java.util.ArrayList();

{
    var list = new_list();

    list[2] = "2";
    list[4] = "4";
    list[3] = "3";
    list[2] = "No.2";
    list[9] = "No.9";
    
    assertEquals(10, list.size);
    assertNull(list[0]);
    assertNull(list[1]);
    assertEquals("No.2", list[2]);
    assertEquals("3", list[3]);
    assertEquals("4", list[4]);
    assertEquals("No.9", list[9]);

    // bad data
    list.~add("No.10");
    list.~add(8,"No.8");
    assertEquals(12, list.size);
    assertEquals("No.8", list[8]);
    assertEquals(null, list[9]);
    assertEquals("No.9", list[10]);
    assertEquals("No.10", list[11]);
}


%>