<%

assertNull(LOCAL("a"));

{
    //TEST: General

    LOCAL("a","abc");
    assertEquals("abc", LOCAL("a"));
}

{
    //TEST: include

    LOCAL("a","abc");
    include "etc/localTest.include.wit";
    assertEquals("def", LOCAL("a"));
}

{
    //TEST: Global function

    LOCAL("a","xxx");
    localTestInClobal("a","xxx");

    localTestInClobal_set("a", "yyy");
    assertEquals("yyy", LOCAL("a"));
}

%>