var b,c,d

var a
  = 111
  + 222
  + 333
  /3
assertEquals(444, a)

b=0
d=a
++
b
c=1

assertEquals(444, a)
assertEquals(a, d)
assertEquals(1, b)
assertEquals(1, c)


//
b= function(x){return x}

assertEquals(123, b(123))

//
a=0
a=b
(() -> 0)()

assertEquals(a, b)

//
a=b
((c)->{})()

assertEquals(a, b)

//
a=b
((d,e)->{})()


assertEquals(a, b)

a=1
var arr = [1,2,3]
c = arr
[a] = [2,3,4]

assertEquals(2, a)
assertEquals(c, arr)


c = arr
[a, d] = [3,4]

assertEquals(c, arr)
assertEquals(3, a)
assertEquals(4, d)

// return test

a = 1
var func = ()->{
  return
  a++
}

var VOID = (()->{return})()

assertEquals(VOID, func())
assertEquals("def", "def")
