<%

var b,c,d

var a 
  = 111
  + 222
  + 333
  /3
assertEquals(a, 444)

b=0
d=a
++
b
c=1

assertEquals(a, 444)
assertEquals(a, d)
assertEquals(b, 1)
assertEquals(c, 1)


//
b= function(x){return x}

assertEquals(b(123), 123)

//
a=0
a=b
(() -> 0)()

assertEquals(a, b)

//
a=b
((c)->{})()

assertEquals(a, b)

//
a=b
((d,e)->{})()


assertEquals(a, b)


// FIXME: Unexpected
a=1
var arr = [1,2,3]
c = arr
[a] = [2,3,4]

assertEquals(a, 2)
assertEquals(c, arr)


c = arr
[a, d] = [3,4]

assertEquals(c, arr)
assertEquals(a, 3)
assertEquals(d, 4)

assertEquals("def", "def")