<%

var mapEmpty = {};

assertEquals(mapEmpty.~size(), 0);

var a = "A"
var b = "B"

var map = {
    a, b,
    id: "9527",
    name: "wit",
    1 : "a",
    "1": "b",
    '1': "c",
    [ -1 ] : "d",
    [ -1-1 ] : "e"
};

assertEquals(map["a"], "A");
assertEquals(map["b"], "B");
assertEquals(map["id"], "9527");
assertEquals(map.name, "wit");
assertEquals(map[1], "a");
assertEquals(map["1"], "b");
assertEquals(map['1'], "c");
assertEquals(map[-1], "d");
assertEquals(map[-2], "e");
assertEquals(map[2], null);

var mapLoose = {
    1 : "a",
};

var mapLoose2 = {
    1 : "a",
    "1": "b",
};


assertEquals(mapLoose.~size(), 1);
assertEquals(mapLoose[1], "a");
assertEquals(mapLoose2.~size(), 2);
assertEquals(mapLoose2[1], "a");
assertEquals(mapLoose2["1"], "b");