<%

{
    var list = new_list();
    list@list_add("a");
    list@list_add("b");


    assertEquals("b",list[1]);
    assertEquals(2,list@list_size());
}
{
    assertEquals("bcd","abcde"@substring(1,4));
}

%>