<%

{
    var list = new_list();
    list_add(list,"a");
    list_add(list,"b");

    assertEquals("b",list[1]);
    assertEquals(2,list_size(list));
}
{
    assertEquals("bcd",substring("abcde",1,4));
}

%>