<%

    @import org.junit.Assert;

    var _assertEquals = native Assert.assertEquals(String, Object, Object);
    var _assertNotEquals = native Assert.assertNotEquals(String, Object, Object);
    var _assertTrue = native Assert.assertTrue(String, boolean);
    var _assertFalse = native Assert.assertFalse(String, boolean);
    var _assertNull = native Assert.assertNull(String, Object);
    var _assertNotNull = native Assert.assertNotNull(String, Object);
    var _assertSame = native Assert.assertSame(String, Object, Object);
    var _assertNotSame = native Assert.assertNotSame(String, Object, Object);
    var _assertArrayEquals = native Assert.assertArrayEquals(String, Object[], Object[]);
    var _assertArrayEquals_chars = native Assert.assertArrayEquals(String, char[], char[]);

    assertTrue = function(object, msg){
        _assertTrue(msg, object);
        assertCount++ ;
    };

    assertFalse = function(object, msg){
        _assertFalse(msg, object);
        assertCount++ ;
    };

    assertEquals = function(first, second, msg){
        _assertEquals(msg, first, second);
        assertCount++ ;
    };

    assertNotEquals = function(first, second, msg){
        _assertNotEquals(msg, first, second);
        assertCount++ ;
    };

    assertNull = function(object, msg){
        _assertNull(msg, object);
        assertCount++ ;
    };

    assertNotNull = function(object, msg){
        _assertNotNull(msg, object);
        assertCount++ ;
    };

    assertSame = function(first, second, msg){
        _assertSame(msg, first, second);
        assertCount++ ;
    };

    assertNotSame = function(first, second, msg){
        _assertNotSame(msg, first, second);
        assertCount++ ;
    };

    assertArrayEquals = function(first, second, msg){
        _assertArrayEquals(msg, first, second);
        assertCount++ ;
    };

    assertArrayEquals_chars = function(first, second, msg){
        _assertArrayEquals_chars(msg, first, second);
        assertCount++ ;
    };

%>