plugins {
  alias libs.plugins.febit.java
  alias libs.plugins.febit.maven.publish
  alias libs.plugins.febit.codegen.module
}

group 'org.febit.wit'
version '3.0.0-SNAPSHOT'

configure(subprojects.findAll {
  !it.name.endsWith('-bom')
}) {
  apply plugin: 'java-library'

  group rootProject.group
  version rootProject.version

  java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17

    withJavadocJar()
    withSourcesJar()
  }

  test {
    useJUnitPlatform()
  }

  repositories {
    mavenCentral()
  }

  dependencyManagement {
    imports {
      mavenBom "${libs.febit.commons.deps.get()}"
    }
  }

  dependencies {
    compileOnly 'org.jspecify:jspecify'
    compileOnly 'com.github.spotbugs:spotbugs-annotations'
    testCompileOnly 'org.jspecify:jspecify'
    testCompileOnly 'com.github.spotbugs:spotbugs-annotations'

    testImplementation 'org.febit:febit-commons-test'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testRuntimeOnly 'org.slf4j:slf4j-simple'
  }
}
