plugins {
  alias libs.plugins.license
  alias libs.plugins.febit.java
  alias libs.plugins.febit.maven.publish
  alias libs.plugins.febit.codegen.module
}

group = 'org.febit.wit'
version = '3.0.0-SNAPSHOT'

subprojects {
  group = rootProject.group
  version = rootProject.version
}

allprojects { subproject ->
  apply plugin: 'com.github.hierynomus.license'

  standardMavenPublish {
    pom { pom ->
      customPom(subproject, pom)
    }
  }

  repositories {
    mavenCentral()
  }

  license {
    mapping {
      java = 'SLASHSTAR_STYLE'
    }
    include '**/*.java'
    exclude '**/Lexer.java'
    exclude '**/ParserImpl.java'
    exclude '**/TokenKinds.java'
    strictCheck = false
    skipExistingHeaders = false
    header = rootProject.file('etc/license-header.txt')
  }
}

configure(subprojects.findAll {
  !it.name.endsWith('-bom')
}) {
  apply plugin: 'java-library'

  java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17

    withJavadocJar()
    withSourcesJar()
  }

  test {
    useJUnitPlatform()
  }

  licenseMain {
    mustRunAfter 'generateModule'
  }

  dependencies {
    implementation(platform(libs.febit.commons.deps))
    implementation(platform(libs.jetty.bom))
    implementation(platform(libs.jetty.ee11.bom))

    compileOnly 'org.jspecify:jspecify'
    compileOnly 'com.github.spotbugs:spotbugs-annotations'
    testCompileOnly 'org.jspecify:jspecify'
    testCompileOnly 'com.github.spotbugs:spotbugs-annotations'

    testImplementation 'org.febit:febit-commons-test'
    testImplementation 'org.eclipse.jetty.ee11:jetty-ee11-servlet'

    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testRuntimeOnly 'org.slf4j:slf4j-simple'
  }
}

static def customPom(Project project, MavenPom pom) {
  if (!project.name.endsWith("-bom")) {
    pom.withXml {
      def root = asNode()
      def dm = root.dependencyManagement?.getAt(0) as Node
      if (dm != null) {
        root.remove(dm)
      }
    }
  }
  pom.with {
    name.set project.name
    description.set project.description
    url.set 'https://github.com/febit/wit'
    organization {
      name = 'Febit'
      url = 'https://github.com/febit'
    }
    licenses {
      license {
        name = 'Apache License, Version 2.0'
        url = 'https://github.com/febit/febit-common/blob/main/LICENSE.txt'
        distribution = 'repo'
      }
    }
    scm {
      url = 'https://github.com/febit/wit'
      connection = 'scm:git:https://github.com/febit/wit.git'
      developerConnection = 'scm:git:https://github.com/febit/wit.git'
    }
    issueManagement {
      system = 'GitHub'
      url = 'https://github.com/febit/wit/issues'
    }
    developers {
      developer {
        id = 'kurt'
        name = 'Kurt Zhu'
        email = 'zqq@febit.org'
        timezone = '+8'
      }
    }
  }
}
