{
    assertNotNull($GLOBAL);
    assertEquals(1, $GLOBAL["one"]);
    assertEquals(2, $GLOBAL["two"]);
    assertEquals("string", $GLOBAL["string"]);
    assertEquals("string2", $GLOBAL["string2"]);
}
