[versions]
hierynomus-license = '0.16.1'
jmh = '1.37'
jmh-plugin = '0.7.2'

febit-commons = '4.0.2'
febit-devkit = '1.6.1'
jakarta-servlet-api='6.1.0'
xbib-jflex = "3.0.2"
zerofs = "0.1.0"
jetty = "12.1.9"

[libraries]
febit-commons-deps = { module = 'org.febit:febit-commons-dependencies', version.ref = 'febit-commons' }
jakarta-servlet-api= { module = 'jakarta.servlet:jakarta.servlet-api', version.ref = 'jakarta-servlet-api' }
zerofs = { module = 'io.roastedroot:zerofs', version.ref = 'zerofs' }
jetty-bom = { module = 'org.eclipse.jetty:jetty-bom', version.ref = 'jetty' }
jetty-ee11-bom = { module = 'org.eclipse.jetty.ee11:jetty-ee11-bom', version.ref = 'jetty' }
jmh-core = { module = 'org.openjdk.jmh:jmh-core', version.ref = 'jmh' }
jmh-generator = { module = 'org.openjdk.jmh:jmh-generator-annprocess', version.ref = 'jmh' }

[plugins]
febit-bom = { id = 'org.febit.standard-bom', version.ref = 'febit-devkit' }
febit-codegen-module = { id = 'org.febit.codegen-module', version.ref = 'febit-devkit' }
febit-java = { id = 'org.febit.standard-java', version.ref = 'febit-devkit' }
febit-maven-publish = { id = 'org.febit.standard-maven-publish', version.ref = 'febit-devkit' }
license = { id = 'com.github.hierynomus.license', version.ref = 'hierynomus-license' }
xbib-jflex = { id = "org.xbib.gradle.plugin.jflex", version.ref = "xbib-jflex" }
jmh = { id = 'me.champeau.jmh', version.ref = 'jmh-plugin' }
