{
    var i = 0;
    var counter = 3;
    for(i : 3..6){
        assertEquals(i, counter);
        counter++;
    }else{
        //assert shouldn't run here
        assertNotNull(null);
    }
    assertEquals(i, 0);
    assertEquals(counter, 7);
}
{
    for(i : 3..6){
    }else{
        //assert shouldn't run here
        assertNotNull(null);
    }
}
