{
    var i = 0;
    var counter = 3;
    for(i : 3..6){
        assertEquals(counter, i);
        counter++;
    }else{
        //assert shouldn't run here
        assertNotNull(null);
    }
    assertEquals(0, i);
    assertEquals(7, counter);
}
{
    for(i : 3..6){
    }else{
        //assert shouldn't run here
        assertNotNull(null);
    }
}
{
    var elseExecuted = false;
    for(i : []) {
        assertTrue(false);
    } else {
        elseExecuted = true;
        assertTrue(true);
    }
    assertTrue(elseExecuted);

    elseExecuted = false;
    for(i : []) {
        break;
    } else {
        elseExecuted = true;
        assertTrue(true);
    }
    assertTrue(elseExecuted);
}
