@import org.febit.wit.exception.ScriptEvaluateException;

{
  var arr = [];

  assertEquals(0, arr.size);
  assertEquals(0, arr.length);
  assertTrue(arr.isEmpty);
}
{

  var arr = [
      "a",
  ];

  assertFalse(arr.isEmpty);
  assertEquals(1, arr.size);
  assertEquals("a", arr[0]);
}
{

  var arr = [
      "a", "b", null
  ];

  assertEquals(3, arr.size);
  assertEquals("a", arr[0]);
  assertEquals("b", arr[1]);
  assertNull(arr[2]);
}
{
  var arr = [];

  assertThrows(native ScriptEvaluateException.class, () -> {
    var x = arr[0];
  });
  assertThrows(native ScriptEvaluateException.class, () -> {
    var x = arr[-1];
  });
  assertThrows(native ScriptEvaluateException.class, () -> {
    var x = arr[null];
  });
  assertThrows(native ScriptEvaluateException.class, () -> {
    var x = arr["x"];
  });

  assertThrows(native ScriptEvaluateException.class, () -> {
    arr[0] = "x";
  });
  assertThrows(native ScriptEvaluateException.class, () -> {
    arr[-1] = "x";
  });
  assertThrows(native ScriptEvaluateException.class, () -> {
    arr[null] = "x";
  });
  assertThrows(native ScriptEvaluateException.class, () -> {
    arr["x"] = "x";
  });
}

