@import org.febit.wit.exception.ScriptEvaluateException;

{
  var arr = [];

  assertEquals(arr.size, 0);
  assertEquals(arr.length, 0);
  assertTrue(arr.isEmpty);
}
{

  var arr = [
      "a",
  ];

  assertFalse(arr.isEmpty);
  assertEquals(arr.size, 1);
  assertEquals(arr[0], "a");
}
{

  var arr = [
      "a", "b", null
  ];

  assertEquals(arr.size, 3);
  assertEquals(arr[0], "a");
  assertEquals(arr[1], "b");
  assertEquals(arr[2], null);
}
{
  var arr = [];

  assertThrows(native ScriptEvaluateException.class, () -> {
    var x = arr[0];
  });
  assertThrows(native ScriptEvaluateException.class, () -> {
    var x = arr[-1];
  });
  assertThrows(native ScriptEvaluateException.class, () -> {
    var x = arr[null];
  });
  assertThrows(native ScriptEvaluateException.class, () -> {
    var x = arr["x"];
  });

  assertThrows(native ScriptEvaluateException.class, () -> {
    arr[0] = "x";
  });
  assertThrows(native ScriptEvaluateException.class, () -> {
    arr[-1] = "x";
  });
  assertThrows(native ScriptEvaluateException.class, () -> {
    arr[null] = "x";
  });
  assertThrows(native ScriptEvaluateException.class, () -> {
    arr["x"] = "x";
  });
}

