var UNDEFINED = (() -> { return; })();

var str

str = ``
assertEquals(str, "")

str = `null: ${null}`
assertEquals(str, "null: ")

str = `undefined: ${UNDEFINED}`
assertEquals(str, "undefined: ")

str = `awesome\t\n script

.`
assertEquals(str, "awesome\t\n script\n\n.")

var id=9527, name="Mr Tang";
var jobs = {
  9527: "Master"
};
str = `${1+2}, ${id}, ${name}, ${jobs[id]}${(()->".")()}`
assertEquals(str, "3, 9527, Mr Tang, Master.")

str = `${((name)->{ var map={func:"bala..bala..bala"}; return "nested function: " + name + " - " + map[name]})("func")}`
assertEquals(str, "nested function: func - bala..bala..bala")

// ScriptParseException: Illegal character '`', not support nesting script string
// str = `${`nested`}.`
// assertEquals(str, "nested.")
