
//----------------------------------------------------
// The following code was generated by CUP v0.12zqq 20130720
// Sat Aug 10 10:08:53 CST 2013
//----------------------------------------------------

package webit.script.core;

/** CUP generated interface containing symbol constants. */
public interface Tokens {
  /* terminals */
  public static final int AT = 77;
  public static final int AS = 20;
  public static final int IDENTIFIER = 79;
  public static final int ANDEQ = 62;
  public static final int GT = 41;
  public static final int NOTEQ = 45;
  public static final int PLUSEQ = 54;
  public static final int RBRACK = 75;
  public static final int CATCH = 15;
  public static final int COMMA = 68;
  public static final int RBRACE = 71;
  public static final int THROW = 13;
  public static final int RPAREN = 73;
  public static final int LBRACK = 74;
  public static final int LT = 40;
  public static final int ANDAND = 50;
  public static final int OROR = 51;
  public static final int LBRACE = 70;
  public static final int LPAREN = 72;
  public static final int XOREQ = 63;
  public static final int INTEGER_LITERAL = 80;
  public static final int NOT = 52;
  public static final int EQGT = 76;
  public static final int VAR = 2;
  public static final int URSHIFTEQ = 61;
  public static final int COMP = 49;
  public static final int EQ = 78;
  public static final int BOOLEAN_LITERAL = 82;
  public static final int MOD = 36;
  public static final int INCLUDE = 25;
  public static final int SUPER = 7;
  public static final int NATIVE = 23;
  public static final int PLUS = 32;
  public static final int QUESTION = 53;
  public static final int WHILE = 12;
  public static final int SWITCH = 8;
  public static final int DO = 11;
  public static final int FOR = 5;
  public static final int RSHIFTEQ = 60;
  public static final int DIV = 35;
  public static final int RETURN = 29;
  public static final int MULT = 34;
  public static final int ELSE = 4;
  public static final int TRY = 14;
  public static final int BREAK = 27;
  public static final int GTEQ = 43;
  public static final int DOT = 66;
  public static final int ECHO = 21;
  public static final int NULL_LITERAL = 85;
  public static final int STRING_LITERAL = 84;
  public static final int EQEQ = 44;
  public static final int EOF = 0;
  public static final int SEMICOLON = 69;
  public static final int THIS = 6;
  public static final int DEFAULT = 10;
  public static final int FUNCTION = 19;
  public static final int MULTEQ = 56;
  public static final int IMPORT = 24;
  public static final int MINUS = 33;
  public static final int LTEQ = 42;
  public static final int TEXT_STATMENT = 87;
  public static final int OR = 48;
  public static final int error = 1;
  public static final int URSHIFT = 39;
  public static final int PLACE_HOLDER_END = 86;
  public static final int DIVEQ = 57;
  public static final int LSHIFTEQ = 59;
  public static final int FINALLY = 16;
  public static final int CONTINUE = 28;
  public static final int IF = 3;
  public static final int INSTANCEOF = 18;
  public static final int MODEQ = 58;
  public static final int MINUSMINUS = 31;
  public static final int COLON = 67;
  public static final int CHARACTER_LITERAL = 83;
  public static final int NATIVE_IMPORT = 26;
  public static final int OREQ = 64;
  public static final int CASE = 9;
  public static final int PLUSPLUS = 30;
  public static final int NEW = 17;
  public static final int RSHIFT = 38;
  public static final int AND = 46;
  public static final int STATIC = 22;
  public static final int UMINUS = 65;
  public static final int LSHIFT = 37;
  public static final int XOR = 47;
  public static final int FLOATING_POINT_LITERAL = 81;
  public static final int MINUSEQ = 55;
}

