// Copyright (c) 2013-2016, febit.org. All Rights Reserved.
package org.febit.wit.parser;

import org.febit.wit.exception.ParseException;
import org.febit.wit.parser.Ast.*;
import org.febit.wit.parser.Ast;
import org.febit.wit.parser.ImportPart;
import org.febit.wit.runtime.ALU;
import org.febit.wit.runtime.ast.*;
import org.febit.wit.runtime.ast.expr.*;
import org.febit.wit.runtime.ast.extra.*;
import org.febit.wit.runtime.ast.oper.*;
import org.febit.wit.runtime.ast.stat.*;
import org.febit.wit.util.ClassNameRope;

import static org.febit.wit.parser.FunctionDeclarePart.ArgumentInfo;

/* Terminals */
terminal Integer    VAR,
                    IF, ELSE,
                    FOR,
                    THIS, SUPER,
                    SWITCH, CASE, DEFAULT,
                    DO, WHILE,
                    THROW, TRY, CATCH, FINALLY,
                    NEW,
                    INSTANCEOF,
                    FUNCTION,
                    ECHO,
                    STATIC, NATIVE,
                    IMPORT, INCLUDE, NATIVE_IMPORT,
                    BREAK, CONTINUE, RETURN,

                    PLUSPLUS, MINUSMINUS,  // ++ ==
                    PLUS, MINUS, MULT, DIV, MOD,  // + - * /
                    LSHIFT, RSHIFT, URSHIFT,  // << >> >>>
                    LT, GT, LTEQ, GTEQ, EQEQ, NOTEQ,  // < > <= >= == !=
                    AND, XOR, OR, COMP,  // & ^ | ~
                    ANDAND, OROR, NOT,  // && || !
                    QUESTION,// ?
                    SELFEQ,  // (+ - * / %)= (<< >> >>>)= (& ^ |)=
                    UMINUS,
                    DOT,  // .
                    COLON, COLONCOLON,  // : ::
                    COMMA,  // ,
                    SEMICOLON,  // ;
                    LBRACE, RBRACE, INTERPOLATION_END, // { }
                    LPAREN, RPAREN,  // ( )
                    LBRACK, RBRACK,  // [ ]
                    LDEBUG, RDEBUG, LRDEBUG,  // [? ?] [?]
                    EQGT,  // =>
                    RPAREN_MINUSGT, MINUSGT, // )-> ->
                    DYNAMIC_DOT, // @ .~
                    DOTDOT,  // ..
                    EQ,   // =
                    TEMPLATE_STRING_START, TEMPLATE_STRING_INTERPOLATION_END;


terminal String     TEMPLATE_STRING_INTERPOLATION_START, TEMPLATE_STRING_END, IDENTIFIER, METHOD_REFERENCE; // Ident, MethodReference
terminal char[]     TEXT_STATEMENT;
terminal Object     DIRECT_VALUE;
terminal Integer    CONST;

/* nonterminal */
nonterminal ClassNameRope classPureName, className;
nonterminal Class<?> javaClass;
nonterminal ScriptAST scriptAST;

/* Statement */
nonterminal Statement statement, ifStat, varPart;
nonterminal IBlock block, caseBlockStat;
nonterminal Expression varAssign;
nonterminal ImportPart importPart1, importPart2;
nonterminal SwitchPart switchPart, switchPart0;
nonterminal AbstractForInPart forInHead, forInPart, lambdaForHead, lambdaForHead2;
nonterminal WhilePart whilePart;
nonterminal TryPart tryPart, catchPart, finallyPart;

/* Expression */
nonterminal Expression expression, expression_statementable;
nonterminal Expression[] mapPropertyDef;
nonterminal NewMapExpr newMapExpr;
nonterminal TemplateStringBuilder templateStringBuilder;
nonterminal Integer superCount;
nonterminal Expression contextValueExpr;

/* function & Lambda */
nonterminal ArgumentInfo funcArg;
nonterminal Expression funcExecuteExpr;
nonterminal FunctionDeclarePart funcHead, funcStatementHead, mapPropertyFuncHead;
nonterminal Expression lambdaExpr;
nonterminal FunctionDeclarePart lambdaExprHead;
nonterminal FunctionDeclarePart lambdaForHead1, lambdaForMapHead1;

/* precedence */
precedence left     SEMICOLON; // ;
precedence left     COMMA; // ,
precedence left     LDEBUG; // [?
precedence left     RBRACK; // ]
precedence left     COLON;  // :
precedence right    SELFEQ, EQ; // (+ - * / %)=  (<< >> >>>)=  (& ^ |)=  =
precedence left     DOTDOT;  // ..
precedence right    QUESTION; // ?
precedence left     OROR; // ||
precedence left     ANDAND; // &&
precedence left     XOR; // ^
precedence left     OR; // |
precedence left     AND; // &
precedence left     EQEQ, NOTEQ; // == !=
precedence left     LT, LTEQ, GT, GTEQ; // < <= > >=  //Unsupport: instanceOf
precedence left     LSHIFT, RSHIFT, URSHIFT; // << >> >>>
precedence left     PLUS, MINUS; // + -
precedence left     MULT, DIV, MOD; // * / %
precedence right    PLUSPLUS, MINUSMINUS, UMINUS, NOT, COMP; // ++ -- - ! ~
precedence left     EQGT;  // =>
precedence right    RPAREN_MINUSGT, MINUSGT; // ->
precedence left     DOT, LBRACK, LBRACE, LPAREN, RPAREN, DYNAMIC_DOT; // . [ { ( ) @


scriptAST       ::= statement[]:list ?
                    {: yield createScriptAST(%list%); :}
                    ;


classPureName   ::= IDENTIFIER:ident
                    {: yield new ClassNameRope(%ident%); :}
                    |classPureName:part DOT IDENTIFIER:ident
                    {: yield (%part%).append(%ident%); :}
                    ;

className       ::= classPureName:part
                    {: yield %part%; :}
                    |className:part LBRACK RBRACK
                    {: yield (%part%).increaseArrayDepth(); :}
                    ;


javaClass       ::= className:nameRope
                    {: yield toClass(%nameRope%, %nameRope.symbol%.pos); :}
                    ;


/* statements  */
statement       ::= expression_statementable:$ SEMICOLON
                    |SEMICOLON
                    {: yield NoopStatement.INSTANCE; :}

                    |LRDEBUG:sym
                    {: yield Ast.breakpointStatement(null, null, %sym.symbol%.pos); :}
                    |LDEBUG:sym expression:label COLON RDEBUG
                    {: yield Ast.breakpointStatement(%label%, null, %sym.symbol%.pos); :}

                    |expression:expr INTERPOLATION_END
                    {: yield Ast.interpolation(%expr%); :}

                    |block:$

                    |ifStat:$

                    //switch
                    |switchPart:part
                    {: yield (%part%).pop(0); :}
                    |IDENTIFIER:label COLON switchPart:part
                    {: yield (%part%).pop(getLabelIndex(%label%)); :}

                    //while
                    |whilePart:part
                    {: yield (%part%).pop(0); :}
                    |IDENTIFIER:label COLON whilePart:part
                    {: yield (%part%).pop(getLabelIndex(%label%)); :}

                    //forIn
                    |forInPart:part
                    {: yield (%part%).pop(0); :}
                    |IDENTIFIER:label COLON forInPart:part
                    {: yield (%part%).pop(getLabelIndex(%label%)); :}

                    //RedirectOut
                    |block:stat EQGT:sym expression:expr SEMICOLON
                    {: yield Ast.renderRedirect(%stat%, Ast.castToAssignable(%expr%), %sym.symbol%.pos); :}

                    //textStat
                    |TEXT_STATEMENT:sym
                    {: yield createTemplateText(%sym%, %sym.symbol%.pos); :}

                    //
                    |CONST IDENTIFIER:ident EQ expression:expr SEMICOLON
                    {: assignConst(%ident%, %expr%, %ident.symbol%.pos); yield NoopStatement.INSTANCE; :}

                    //var
                    |VAR varPart[COMMA]:parts SEMICOLON
                    {: yield Ast.statementGroup(%parts%, %parts.symbol%.pos); :}

                    //echoStat
                    |ECHO:sym expression:expr SEMICOLON
                    {: yield Ast.echo(%expr%, %sym.symbol%.pos); :}

                    //@import
                    |NATIVE_IMPORT:sym classPureName:nameRope SEMICOLON
                    {: registerClass(%nameRope%, %sym.symbol%.pos); yield NoopStatement.INSTANCE; :}

                    //BREAK
                    |BREAK:sym IDENTIFIER:label? SEMICOLON
                    {: yield new Break(getLabelIndex(%label%), %sym.symbol%.pos); :}

                    // CONTINUE
                    |CONTINUE:sym IDENTIFIER:label? SEMICOLON
                    {: yield new Continue(getLabelIndex(%label%), %sym.symbol%.pos); :}

                    // RETURN
                    |RETURN:sym expression:expr? SEMICOLON
                    {: yield Ast.returnWith(%expr%, %sym.symbol%.pos); :}

                    // importStat
                    |importPart1:part SEMICOLON
                    {: yield (%part%).pop(this.script); :}
                    |importPart2:part SEMICOLON
                    {: yield (%part%).pop(this.script); :}

                    //includeStat
                    |INCLUDE:sym expression:expr newMapExpr:paramsExpr? SEMICOLON
                    {: yield new Include(%expr%, %paramsExpr%, this.script.path(), %sym.symbol%.pos); :}

                    //funcStatement
                    |funcStatementHead:part LBRACE statement[]:list? RBRACE
                    {: yield (%part%).pop(%list%); :}

                    //
                    |(catchPart:$ | finallyPart:$):part
                    {: yield (%part%).pop(); :}

                    //
                    | THROW:sym expression:expr SEMICOLON
                    {: yield new Throw(%expr%, %sym.symbol%.pos); :}
                    ;


varAssign       ::= IDENTIFIER:ident EQ:sym (expression:$ | varAssign:$):expr
                    {: yield Ast.assign(declareVarAndCreateContextValue(%ident%, %ident.symbol%.pos), %expr%, %sym.symbol%.pos); :}
                    ;

varPart         ::= varAssign:$
                    | IDENTIFIER:ident
                    {: yield declareVar(%ident%, %ident.symbol%.pos); :}
                    | LBRACK IDENTIFIER[COMMA]:idents RBRACK EQ:sym expression:expr
                    {: yield Ast.groupAssign(declareVarAndCreateContextValues(%idents%, %idents.symbol%.pos), %expr%, %sym.symbol%.pos); :}
                    ;


importPart1     ::= IMPORT:sym expression:expr newMapExpr:paramsExpr?
                    {: yield new ImportPart(%expr%, %paramsExpr%, %sym.symbol%.pos); :}
                    ;


importPart2     ::= importPart1:part IDENTIFIER:ident
                    {: yield (%part%).append(%ident%, createContextValue(0, %ident%, %ident.symbol%.pos)); :}
                    |importPart1:part contextValueExpr:valueExpr EQ IDENTIFIER:ident
                    {: yield (%part%).append(%ident%, %valueExpr%); :}
                    |importPart2:part COMMA IDENTIFIER:ident
                    {: yield (%part%).append(%ident%, createContextValue(0, %ident%, %ident.symbol%.pos)); :}
                    |importPart2:part COMMA contextValueExpr:valueExpr EQ IDENTIFIER:ident
                    {: yield (%part%).append(%ident%, %valueExpr%); :}
                    ;


block           ::= (LBRACE {: variants.shiftFrame(); yield null; :}) statement[]:list? RBRACE
                    {: yield Ast.block(%list%, variants.unshiftFrame(), %list.symbol%.pos); :}
                    ;


tryPart         ::= (TRY LBRACE {: variants.shiftFrame(); yield null; :}) statement[]:list? RBRACE
                    {: yield createTryPart(%list%, variants.unshiftFrame(), %list.symbol%.pos); :}
                    ;

catchPart       ::= tryPart:part (CATCH LPAREN IDENTIFIER:ident RPAREN LBRACE {: variants.shiftFrame(); yield variants.assignVar(%ident%, %ident.symbol%.pos); :}):varIndex statement[]:list? RBRACE
                    {: yield (%part%).setCatchStat((Integer)(%varIndex%), Ast.block(%list%, variants.unshiftFrame(), %list.symbol%.pos)); :}
                    ;

finallyPart     ::= (tryPart:$ | catchPart:$):part (FINALLY LBRACE {: variants.shiftFrame(); yield null; :}) statement[]:list? RBRACE
                    {: yield (%part%).setFinalStat(Ast.block(%list%, variants.unshiftFrame(), %list.symbol%.pos)); :}
                    ;


ifStat          ::= IF:sym LPAREN expression:expr RPAREN block:body (ELSE block:$ | ELSE ifStat:$):elseBody?
                    {: yield Ast.ifStatement(%expr%, %body%, (Statement) (%elseBody%), %sym.symbol%.pos); :}
                    ;

forInHead       ::= FOR:sym LPAREN IDENTIFIER:item COLON expression:items RPAREN
                    {: yield new ForInPart(%item%, %items%, this.variants, %sym.symbol%.pos); :}
                    |FOR:sym LPAREN IDENTIFIER:key COMMA IDENTIFIER:value COLON expression:map RPAREN
                    {: yield new ForMapPart(%key%, %value%, %map%, this.variants, %sym.symbol%.pos); :}
                    ;


lambdaForHead1  ::= FOR LPAREN IDENTIFIER:ident MINUSGT:sym
                    {: yield new FunctionDeclarePart(this.variants, %sym.symbol%.pos).appendArg(%ident%); :}
                    ;


lambdaForMapHead1   ::= FOR LPAREN IDENTIFIER:key COMMA IDENTIFIER:value MINUSGT:sym
                    {: yield new FunctionDeclarePart(this.variants, %sym.symbol%.pos).appendArg(%key%).appendArg(%value%); :}
                    ;


lambdaForHead2  ::= lambdaForHead1:part expression:expr COLON
                    {: yield new ForInPart((%part%).getArg(0), (%part%).popFunctionDeclare(%expr%), this.variants, %part.symbol%.pos); :}
                    |lambdaForHead1:part LBRACE statement[]:list RBRACE COLON
                    {: yield new ForInPart((%part%).getArg(0), (%part%).popFunctionDeclare(%list%), this.variants, %part.symbol%.pos); :}
                    |lambdaForMapHead1:part expression:expr COLON
                    {: yield new ForMapPart((%part%).getArg(0), (%part%).getArg(1), (%part%).popFunctionDeclare(%expr%), this.variants, %part.symbol%.pos); :}
                    |lambdaForMapHead1:part LBRACE statement[]:list RBRACE COLON
                    {: yield new ForMapPart((%part%).getArg(0), (%part%).getArg(1), (%part%).popFunctionDeclare(%list%), this.variants, %part.symbol%.pos); :}
                    ;


lambdaForHead   ::= lambdaForHead2:part expression:items RPAREN
                    {: yield (%part%).setCollectionExpr(%items%); :}
                    ;


forInPart       ::= (forInHead:$ | lambdaForHead:$):part LBRACE statement[]:list? RBRACE (ELSE block:$):elseBody?
                    {: yield (%part%).setBodies(Ast.block(%list%, variants.unshiftFrame(), %list.symbol%.pos), %elseBody%); :}
                    ;


whilePart       ::= WHILE:sym LPAREN expression:whileExpr RPAREN block:body
                    {: yield new WhilePart(%whileExpr%, %body%, true, %sym.symbol%.pos); :}
                    |DO:sym block:body WHILE LPAREN expression:whileExpr RPAREN SEMICOLON
                    {: yield new WhilePart(%whileExpr%, %body%, false, %sym.symbol%.pos); :}
                    ;


caseBlockStat   ::= {: variants.shiftFrame(); yield null; :} statement[]:list?
                    {: yield Ast.block(%list%, variants.unshiftFrame(), %list.symbol%.pos); :}
                    ;


switchPart0     ::=
                    {: yield new SwitchPart(); :}
                    | CASE:sym MINUS:negative? DIRECT_VALUE:key COLON caseBlockStat:body switchPart0:part
                    {: yield (%part%).appendCase((%negative% == null)?(%key%):ALU.negative(%key%), %body%, %sym.symbol%.pos); :}
                    | DEFAULT:sym COLON caseBlockStat:body switchPart0:part
                    {: yield (%part%).appendCase(null, %body%, %sym.symbol%.pos); :}
                    ;


switchPart      ::= SWITCH:sym LPAREN expression:switchExpr RPAREN LBRACE TEXT_STATEMENT ? switchPart0:part RBRACE
                    {: yield (%part%).setSwitchExpr(%switchExpr%, %sym.symbol%.pos); :}
                    ;



/* Expressions */

expression_statementable ::=
                    //assignOp =
                    expression:lexpr EQ:sym expression:expr
                    {: yield Ast.assign(Ast.castToAssignable(%lexpr%), %expr%, %sym.symbol%.pos); :}

                    |LBRACK expression[COMMA]:list COMMA? RBRACK EQ:sym expression:expr
                    {: yield Ast.groupAssign(Ast.toExpressionArray(%list%), %expr%, %sym.symbol%.pos); :}

                    // Increase ++
                    |PLUSPLUS:sym expression:expr
                    {: yield Ast.increaseAndGet(Ast.castToAssignable(%expr%), %sym.symbol%.pos); :}
                    |expression:expr PLUSPLUS:sym
                    {: yield Ast.getAndIncrease(Ast.castToAssignable(%expr%), %sym.symbol%.pos); :}

                    // Decrease --
                    |MINUSMINUS:sym expression:expr
                    {: yield Ast.decreaseAndGet(Ast.castToAssignable(%expr%), %sym.symbol%.pos); :}
                    |expression:expr MINUSMINUS:sym
                    {: yield Ast.getAndDecrease(Ast.castToAssignable(%expr%), %sym.symbol%.pos); :}

                    //selfOp
                    |expression:lexpr SELFEQ:sym expression:rexpr
                    {: yield Ast.selfOperator(%lexpr%, %sym%, %rexpr%, %sym.symbol%.pos); :}

                    //
                    |funcExecuteExpr:$
                    ;


expression      ::= expression_statementable:$

                    |LDEBUG:sym expression:expr RDEBUG
                    {: yield Ast.breakpointExpr(null, %expr%, %sym.symbol%.pos); :}

                    |LDEBUG:sym expression:label COLON expression:expr RDEBUG
                    {: yield Ast.breakpointExpr(%label%, %expr%, %sym.symbol%.pos); :}

                    //bitNotOp ~
                    |COMP:sym expression:expr
                    {: yield Ast.operator(%expr%, %sym.symbol%); :}

                    //negativeOp  -
                    |MINUS:sym expression:expr %prec UMINUS
                    {: yield Ast.operator(%expr%, %sym.symbol%); :}

                    //notOp !
                    |NOT:sym expression:expr
                    {: yield Ast.operator(%expr%, %sym.symbol%); :}

                    // Fixed property .
                    |expression:expr DOT:sym IDENTIFIER:ident
                    {: yield Ast.property(%expr%, %ident%, %sym.symbol%.pos); :}

                    // property []
                    |expression:lexpr LBRACK:sym expression:rexpr RBRACK
                    {: yield Ast.property(%lexpr%, %rexpr%, %sym.symbol%.pos); :}

                    /***********  binaries *************/
                    //-- binary:  *
                    |expression:lexpr MULT:sym expression:rexpr
                    {: yield Ast.binaryOperator(%lexpr%, %sym.symbol%, %rexpr%); :}
                    //-- binary:  /
                    |expression:lexpr DIV:sym expression:rexpr
                    {: yield Ast.binaryOperator(%lexpr%, %sym.symbol%, %rexpr%); :}
                    //-- binary:  %
                    |expression:lexpr MOD:sym expression:rexpr
                    {: yield Ast.binaryOperator(%lexpr%, %sym.symbol%, %rexpr%); :}
                    //-- binary:  +
                    |expression:lexpr PLUS:sym expression:rexpr
                    {: yield Ast.binaryOperator(%lexpr%, %sym.symbol%, %rexpr%); :}
                    //-- binary:  -
                    |expression:lexpr MINUS:sym expression:rexpr
                    {: yield Ast.binaryOperator(%lexpr%, %sym.symbol%, %rexpr%); :}
                    //-- binary:  <<
                    |expression:lexpr LSHIFT:sym expression:rexpr
                    {: yield Ast.binaryOperator(%lexpr%, %sym.symbol%, %rexpr%); :}
                    //-- binary:  >>
                    |expression:lexpr RSHIFT:sym expression:rexpr
                    {: yield Ast.binaryOperator(%lexpr%, %sym.symbol%, %rexpr%); :}
                    //-- binary:  >>>
                    |expression:lexpr URSHIFT:sym expression:rexpr
                    {: yield Ast.binaryOperator(%lexpr%, %sym.symbol%, %rexpr%); :}
                    //-- binary:  <
                    |expression:lexpr LT:sym expression:rexpr
                    {: yield Ast.binaryOperator(%lexpr%, %sym.symbol%, %rexpr%); :}
                    //-- binary:  <=
                    |expression:lexpr LTEQ:sym expression:rexpr
                    {: yield Ast.binaryOperator(%lexpr%, %sym.symbol%, %rexpr%); :}
                    //-- binary:  >
                    |expression:lexpr GT:sym expression:rexpr
                    {: yield Ast.binaryOperator(%lexpr%, %sym.symbol%, %rexpr%); :}
                    //-- binary:  >=
                    |expression:lexpr GTEQ:sym expression:rexpr
                    {: yield Ast.binaryOperator(%lexpr%, %sym.symbol%, %rexpr%); :}
                    //-- binary:  ==
                    |expression:lexpr EQEQ:sym expression:rexpr
                    {: yield Ast.binaryOperator(%lexpr%, %sym.symbol%, %rexpr%); :}
                    //-- binary:  !=
                    |expression:lexpr NOTEQ:sym expression:rexpr
                    {: yield Ast.binaryOperator(%lexpr%, %sym.symbol%, %rexpr%); :}
                    //-- binary:  &
                    |expression:lexpr AND:sym expression:rexpr
                    {: yield Ast.binaryOperator(%lexpr%, %sym.symbol%, %rexpr%); :}
                    //-- binary:  |
                    |expression:lexpr OR:sym expression:rexpr
                    {: yield Ast.binaryOperator(%lexpr%, %sym.symbol%, %rexpr%); :}
                    //-- binary:  ^
                    |expression:lexpr XOR:sym expression:rexpr
                    {: yield Ast.binaryOperator(%lexpr%, %sym.symbol%, %rexpr%); :}
                    //-- binary:  &&
                    |expression:lexpr ANDAND:sym expression:rexpr
                    {: yield Ast.binaryOperator(%lexpr%, %sym.symbol%, %rexpr%); :}
                    //-- binary:  ..
                    |expression:lexpr DOTDOT:sym expression:rexpr
                    {: yield Ast.binaryOperator(%lexpr%, %sym.symbol%, %rexpr%); :}
                    //-- binary:  ||
                    |expression:lexpr OROR:sym expression:rexpr
                    {: yield Ast.binaryOperator(%lexpr%, %sym.symbol%, %rexpr%); :}

                    // ? :
                    |expression:ifExpr QUESTION:sym expression:lexpr COLON expression:rexpr
                    {: yield Ast.ifOperator(%ifExpr%, %lexpr%, %rexpr%, %sym.symbol%.pos); :}

                    //
                    |DIRECT_VALUE:sym
                    {: yield Ast.directValue(%sym.symbol%); :}

                    // ()
                    |LPAREN expression:$ RPAREN

                    //funcDeclareExpr
                    |funcHead:part LBRACE statement[]:list? RBRACE
                    {: yield (%part%).pop(%list%); :}

                    //arrayValue
                    |LBRACK:sym RBRACK
                    {: yield Ast.emptyArray(%sym.symbol%.pos); :}
                    |LBRACK:sym expression[COMMA]:list COMMA? RBRACK
                    {: yield Ast.newArray(%sym.symbol%.pos, %list%); :}

                    //NativeNewArrayDeclareExpression
                    |NATIVE:sym LBRACK RBRACK javaClass:javaClass
                    {: yield createNativeNewArrayDeclareExpression(%javaClass%, %sym.symbol%.pos); :}

                    //nativeMethodExpr
                    |NATIVE:sym classPureName:nameRope DOT IDENTIFIER:ident LPAREN javaClass[COMMA]:list? RPAREN
                    {: yield createNativeMethodDeclareExpression(toClass(%nameRope%, %nameRope.symbol%.pos), %ident%, %list%, %sym.symbol%.pos); :}

                    //native static field
                    |NATIVE classPureName:nameRope
                    {: yield createNativeStaticValue(%nameRope%, %nameRope.symbol%.pos); :}

                    //nativeConstructorExpr
                    |NATIVE:sym NEW classPureName:nameRope LPAREN javaClass[COMMA]:list? RPAREN
                    {: yield createNativeConstructorDeclareExpression(toClass(%nameRope%, %nameRope.symbol%.pos), %list%, %sym.symbol%.pos); :}

                    |METHOD_REFERENCE:ref
                    {: yield createMethodReference(%ref%, %ref.symbol%.pos); :}

                    |contextValueExpr:$
                    |newMapExpr:$

                    //Lambda
                    |lambdaExpr:$

                    // script string
                    |templateStringBuilder:part TEMPLATE_STRING_END:end
                    {: yield (%part%).expr(Ast.directValue(%end.symbol%)).build(); :}
                    ;

// super
superCount      ::= SUPER DOT
                    {: yield 1; :}
                    |superCount:count SUPER DOT
                    {: yield %count% + 1; :}
                    ;


// ident  super...ident  this.ident

contextValueExpr    ::= IDENTIFIER:ident
                        {: yield createContextValue(0, %ident%, %ident.symbol%.pos); :}
                        |superCount:count IDENTIFIER:ident
                        {: yield createContextValue(%count%, %ident%, %ident.symbol%.pos); :}
                        |FOR DOT IDENTIFIER:ident
                        {: yield createContextValue(0, ("for." + %ident%), %ident.symbol%.pos); :}
                        |superCount:count FOR DOT IDENTIFIER:ident
                        {: yield createContextValue(%count%, ("for." + %ident%), %ident.symbol%.pos); :}
                        ;

// map {key:expr, ...}

mapPropertyDef        ::= DIRECT_VALUE:key COLON expression:expr
                        {: yield new Expression[]{Ast.directValue(%key.symbol%), %expr%}; :}
                        |MINUS:sym DIRECT_VALUE:key COLON expression:expr
                        {: yield new Expression[]{Ast.directValue(ALU.negative(%key%), %key.symbol%.pos), %expr%}; :}
                        |IDENTIFIER:ident
                        {: yield new Expression[]{Ast.directValue(%ident.symbol%), createContextValue(0, %ident%, %ident.symbol%.pos)}; :}
                        |IDENTIFIER:ident COLON expression:expr
                        {: yield new Expression[]{Ast.directValue(%ident.symbol%), %expr%}; :}
                       // |IDENTIFIER:ident mapPropertyFuncHead:part LBRACE statement[]:list? RBRACE
                       // {: yield new Expression[]{Ast.directValue(%ident.symbol%), (%part%).pop(%list%)}; :}
                        |LBRACK expression:key RBRACK COLON expression:expr
                        {: yield new Expression[]{%key%, %expr%}; :}
                        ;


newMapExpr            ::= LBRACE:sym RBRACE
                        {: yield Ast.newMap(null, %sym.symbol%.pos); :}
                        |LBRACE:sym mapPropertyDef[COMMA]:list COMMA? RBRACE
                        {: yield Ast.newMap(%list%, %sym.symbol%.pos); :}
                        ;


templateStringBuilder  ::= TEMPLATE_STRING_START:sym
                            {: yield Ast.templateStringBuilder().pos(%sym.symbol%.pos); :}
                            | templateStringBuilder:part TEMPLATE_STRING_INTERPOLATION_START:start expression:expr TEMPLATE_STRING_INTERPOLATION_END
                            {: yield (%part%).expr(Ast.directValue(%start.symbol%)).expr(%expr%); :}
                            ;

/* function  */
funcArg             ::= IDENTIFIER:ident
                        {: yield new ArgumentInfo(%ident%, null); :}
                        | IDENTIFIER:ident EQ expression:expr
                        {: yield new ArgumentInfo(%ident%, AstUtils.evalConst(%expr%)); :}
                        ;


funcStatementHead   ::= FUNCTION:sym IDENTIFIER:ident LPAREN funcArg[COMMA]:args? RPAREN
                        {: yield new FunctionDeclarePart(%ident%, this.variants, %ident.symbol%.pos).appendArgs(%args%); :}
                        ;

// mapPropertyFuncHead ::= LPAREN:sym funcArg[COMMA]:args? RPAREN
//                         {: yield new FunctionDeclarePart(this.variants, %sym.symbol%.pos).appendArgs(%args%); :}
//                         ;

funcHead            ::= FUNCTION:sym LPAREN funcArg[COMMA]:args? RPAREN
                        {: yield new FunctionDeclarePart(this.variants, %sym.symbol%.pos).appendArgs(%args%); :}
                        ;

funcExecuteExpr     ::= expression:funcExpr LPAREN RPAREN
                        {: yield Ast.functionCall(%funcExpr%, Ast.emptyExpressions(), %funcExpr.symbol%.pos); :}
                        |expression:funcExpr LPAREN expression[COMMA]:list COMMA? RPAREN
                        {: yield Ast.functionCall(%funcExpr%, Ast.toExpressionArray(%list%), %funcExpr.symbol%.pos); :}
                        |expression:param0 DYNAMIC_DOT IDENTIFIER:ident LPAREN RPAREN
                        {: yield Ast.dynamicNativeMethodCall(%param0%, %ident%, Ast.emptyExpressions(), %ident.symbol%.pos); :}
                        |expression:param0 DYNAMIC_DOT IDENTIFIER:ident LPAREN expression[COMMA]:list COMMA? RPAREN
                        {: yield Ast.dynamicNativeMethodCall(%param0%, %ident%, Ast.toExpressionArray(%list%), %ident.symbol%.pos); :}
                        ;


/* lambda */
lambdaExprHead      ::= IDENTIFIER:ident MINUSGT:sym
                        {: yield new FunctionDeclarePart(this.variants, %sym.symbol%.pos).appendArg(%ident%); :}
                        |LPAREN funcArg[COMMA]:args? RPAREN_MINUSGT:sym
                        {: yield new FunctionDeclarePart(this.variants, %sym.symbol%.pos).appendArgs(%args%); :}
                        ;


lambdaExpr          ::= lambdaExprHead:part expression:expr
                        {: yield (%part%).pop(%expr%); :}
                        |lambdaExprHead:part LBRACE statement[]:list RBRACE
                        {: yield (%part%).pop(%list%); :}
                        ;

