var mapEmpty = {};

assertEquals(0, mapEmpty.~size());

var a = "A"
var b = "B"

var map = {
    a, b,
    id: "9527",
    name: "wit",
    1 : "a",
    "1": "b",
    '1': "c",
    - 11 : "negative",
    [ -1 ] : "d",
    [ -1-1 ] : "e"
};

assertEquals("A", map["a"]);
assertEquals("B", map["b"]);
assertEquals("9527", map["id"]);
assertEquals("wit", map.name);
assertEquals("a", map[1]);
assertEquals("b", map["1"]);
assertEquals("c", map['1']);
assertEquals("d", map[-1]);
assertEquals("e", map[-2]);
assertEquals("negative", map[-11]);
assertNull(map[2]);

var mapLoose = {
    1 : "a",
};

var mapLoose2 = {
    1 : "a",
    "1": "b",
};


assertEquals(1, mapLoose.~size());
assertEquals("a", mapLoose[1]);
assertEquals(2, mapLoose2.~size());
assertEquals("a", mapLoose2[1]);
assertEquals("b", mapLoose2["1"]);
