plugins {
  alias libs.plugins.xbib.jflex
}

description = 'Wit Core'

ext {
  moduleName = 'Wit Core'
}

tasks.named('sourcesJar') {
  mustRunAfter 'generateJflex'
}

tasks.named('licenseMain') {
  mustRunAfter 'generateJflex'
}

tasks.withType(Javadoc).configureEach {
  exclude 'org/febit/wit_shaded/**'
}

def cupRuntime = configurations.create('cup')

dependencies {
  api 'org.slf4j:slf4j-api'
  compileOnly libs.jakarta.servlet.api

  cup files('src/main/cup/java_cup_wit-20260218.jar')

  testImplementation 'commons-io:commons-io'
  testImplementation libs.jakarta.servlet.api
  testImplementation libs.zerofs
}

def PKG_CORE = 'org/febit/wit/parser'
def parserSrcDir = layout.buildDirectory.dir("generated/sources/parser")
def parserResDir = layout.buildDirectory.dir("generated/resources/parser")

sourceSets.main {
  java.srcDir parserSrcDir
  resources.srcDir parserResDir
}

tasks.register('generateParser') {
  doLast {
    providers.javaexec({ JavaExecSpec exec ->
      exec.setClasspath(cupRuntime)
      exec.mainClass.set("java_cup.Main")
      exec.args(
          '-exception', 'ScriptParseException',
          '-symbols', 'TokenKinds',
          '-destdir', parserSrcDir.get().dir(PKG_CORE).getAsFile().absolutePath,
          '-destresdir', parserResDir.get().dir(PKG_CORE).getAsFile().absolutePath,
          file('src/main/cup/Parser.cup').absolutePath
      )
    }).result.get()
  }
}

compileJava.dependsOn(generateParser)
