assertNotNull($GLOBAL["moduleTest_a_1"]);
assertNotNull($GLOBAL["moduleTest_a_2"]);

$GLOBAL["moduleTest_a"] = ($GLOBAL["moduleTest_a"] || 0)  + 1;
$GLOBAL["module-all"] = ($GLOBAL["module-all"] || 0)  + 1;
