@import org.febit.wit.exception.ScriptEvaluateException;
{
  // Default branch before case branch
  var func = function(a) {
    var value = "unset";
    switch (a) {
      default -> value = "default";
      case 1 -> value = "1";
    };
    return value;
  };
  assertEquals("1", func(1));
  assertEquals("default", func(2));
}
{
  // Default branch before case branch
  var func = function(a) {
    var value = "unset";
    switch (a) {
      default -> {
        value = "default";
      }
      case 1 -> {
        value = "1";
      }
    };
    return value;
  };
  assertEquals("1", func(1));
  assertEquals("default", func(2));
}
{
  // Labelled switch
  var func = function(a) {
    var value = "unset";
    outer: switch (a) {
      default -> value = "default";
      case 1 -> value = "1";
      case 2 -> {
        value = "2";
        for (i : 0..4) {
          if (i == 2) {
            break outer;
          }
          value += "|" + i;
        }
      }
    };
    return value;
  };
  assertEquals("1", func(1));
  assertEquals("2|0|1", func(2));
  assertEquals("default", func(3));
}
{
  // Without default branch
  var func = function(a) {
    var value = "unset";
    switch (a) {
      case 1 -> value = "1";
      case 2 -> value = "2";
    };
    return value;
  };
  assertEquals("1", func(1));
  assertEquals("2", func(2));

  assertThrows(native ScriptEvaluateException.class, () -> {
      func(3);
  });
}
{
  // null case
  var func = function(a) {
    var value = "unset";
    switch (a) {
      case null -> value = "null";
      default -> value = "default";
    };
    return value;
  };
  assertEquals("null", func(null));
  assertEquals("default", func(1));
}
