<%

var map = {
    id: "9527",
    "my name": "Wit",
    [101] : 1,
    [102] : 2,
    [111] : 11
};

var xxx;
var xxxFlag = 0;
xxx =function(val){
xxxFlag ++;
if(true){
echo "aaaa";
return;
}
    echo val != "inner";
    echo "\n";
    return null;
};

xxx("outer");

{
@import java.util.Map;
@import java.lang.System;

var map_put = native Map.put(Object,Object);
var now = native System.currentTimeMillis();

var func =function(){
    echo arguments[0];
    return null;
};

var out,out2;
{
echo 1+1;
echo '\n';
} => out;

var map={1:1,2:2};
map_put(map,3,3);

echo "\n===> map\n";
for(k,v : map){
    echo k+ " : "+ v;
    echo "|";
    echo for.iter.index;
    echo "\n";
}
echo "\n===<\n";

map.~put(4);
map.~put(5,"sdasd\
dsdasd\
\tasdasdas\n\
");
map.~put(6,null);
map.~put(null,null);
%>${map}|${now()}|OUT:${out}<%

}%>
